[package]
name = "strum_tests"
version = "0.19.4"
edition = "2018"
authors = ["Peter Glotfelty <peglotfe@microsoft.com>"]

[dependencies]
strum = { path = "../strum", features = ["derive"] }
strum_macros = { path = "../strum_macros", features = [] }
clap = "2.33.0"
enum_variant_type = "0.2.0"
structopt = "0.2.18"

[build-dependencies]
version_check = "0.9.2"