[package]
name = "strum_macros"
version = "0.2.2"
authors = ["Peter Glotfelty <peglotfe@microsoft.com>"]
license = "MIT"

description = "Helpful macros for working with enums and strings"
keywords = ["enum", "string", "macros", "proc-macros"]
categories = ["development-tools::procedural-macro-helpers", "parsing"]

documentation = "https://docs.rs/strum"
homepage = "https://github.com/Peternator7/strum"
readme = "../README.md"

[lib]
proc-macro = true
name = "strum_macros"

[dependencies]
quote = "0.3.12"
syn = "0.11.4"
